DROP TABLE IF EXISTS urls CASCADE;

CREATE TABLE urls (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE urls_check (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code INT,
    title VARCHAR(255),
    h1 VARCHAR(63),
    description TEXT,
    created_at TIMESTAMP,
    url_id INT NOT NULL
);

ALTER TABLE urls_check
ADD CONSTRAINT fk_urls_urls_check
    FOREIGN KEY (url_id)
    REFERENCES urls(id)
    ON DELETE CASCADE;