DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE url_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code INT,
    title VARCHAR(255),
    h1 VARCHAR(63),
    description TEXT,
    created_at TIMESTAMP,
    url_id BIGINT NOT NULL,
    CONSTRAINT fk_url_checks_url_id
        FOREIGN KEY (url_id)
            REFERENCES urls(id)
            ON DELETE CASCADE
);
